export interface InlineServiceTemplate {
  service?: {
    name?: never; // is generated by framework
    [key: string]: any;
  };

  provider?: {
    name?: never; // cannot overwrite framework setting
    stage?: never; // cannot set stage in template

    [key: string]: any;
  };

  [key: string]: any;
}
